### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by entelecheia** [chu-aie/dsecon-2023#11]
## Summary

Add a project proposal file where each student submits a project proposal for their course project.

## Tasks

- [ ] Copy the "proposal.md" file in the `book/projects/id` to the `book/projects/[yourid]` folder from your forked repository
- [ ] Complete the project proposal
  - Should include all sections in the template
- [ ] Review project proposals and make an pull request
  - Make sure scope is appropriate and implementation plan is feasible

## Acceptance Criteria

- Students have a project proposal file
- Project proposals are submitted by each student
- Feedback is provided on each proposal

## 요약

각 학생이 수강 프로젝트에 대한 프로젝트 제안서를 제출하는 프로젝트 제안 파일을 추가합니다.

## 작업

- [ ] 'book/project/id'에 있는 'proposal.md ' 파일을 포크된 저장소의 'book/project/[yourid]' 폴더에 복사합니다
- [ ] 프로젝트 제안서 작성
  - 템플릿의 모든 섹션을 포함해야 합니다
- [ ] 프로젝트 제안서 검토 및 철회 요청
  - 범위가 적절하고 구현 계획이 가능한지 확인

## 합격기준

- 학생들은 프로젝트 제안 파일을 가지고 있습니다
- 각 학생이 프로젝트 제안서를 제출합니다
- 각 제안에 대한 피드백을 제공
